### ISSUE TITLE
Include Stoll's scripts

### ISSUE THREAD

**Issue by edgarcosta** [edgarcosta/CHIMP#2]
http://www.mathe2.uni-bayreuth.de/stoll/magma/index.html

**Comment by edgarcosta** [comment]
@rbommel, do you have specific suggestions of what to include?

To me it seems that the relevant files would be:
- Computation of the Mordell-Weil group of Jacobians of genus 2
- chabauty-MWS.m
- MWSieve-new.m

**Comment by rbommel** [comment]
Maybe also G3Hyp.spec, G3Hyp.m, G3HypHelp.m. That also seems to be a package. This and the first one you mentioned are most relevant for me personally, but I think the others also have great merit.

**Comment by alexjbest** [comment]
+1 for adding G3Hyp.spec, G3Hyp.m, G3HypHelp.m.

**Comment by edgarcosta** [comment]
done.

I only added G3Hyp.spec, G3Hyp.m, G3HypHelp.m.
