### ISSUE TITLE
Branch not specified for Magma and IntegralPointsConic

### ISSUE THREAD

**Issue by SamSchiavone** [edgarcosta/CHIMP#4]
I got the error
```
fatal: Needed a single revision
Unable to find current origin/master revision in submodule path 'IntegralPointsConic'
```
when pulling with `--recurse-submodules`. Adding `branch = main` in `.gitmodules` to the two submodules Magma and IntegralPointsConic resolved the issue.

**Comment by edgarcosta** [comment]
fixed. Thanks!
